name: Docker build

on:
  workflow_run:
    workflows: ["Node.js CI"]
    types:
      - completed

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag lalkalol1907/mujahid-v2:$(date +%s)
